---
title: "Math-Bridge-Final"
author: "A.S"
date: "August 12, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(hflights)
library(MASS)
```

#### Probability
```{r}
hflights_df = hflights[c("ArrDelay", "DepDelay")]
hflights_df$ArrDelay[is.na(hflights_df$ArrDelay)] = 0
hflights_df$DepDelay[is.na(hflights_df$DepDelay)] = 0

X = hflights_df$ArrDelay
Y = hflights_df$DepDelay

length(X)
head(X, 10)
head(Y, 10)
summary(X)
summary(Y)

ggplot(hflights_df, aes(x=X)) + geom_histogram(binwidth = 1)  + xlim ( -100, 100) + ggtitle("Arrivals (X)")
ggplot(hflights_df, aes(x=Y)) + geom_histogram(binwidth = 1)  + xlim ( -100, 100) + ggtitle("Departures (Y)")

# Calculate 3rd quartile of X, mean of X, Standard Deviation of X
x = round(quantile(X, 0.75, na.rm = TRUE), 4)
meanX = round(mean(X, na.rm=TRUE), 4) 
stdX = round(sqrt(var(X, na.rm=TRUE)), 4)
xvalues = c("3rd quartile(X)=", x, "mean(X)=", meanX, "Standard Deviation(X)=", stdX)
print(paste(xvalues, collapse=" "))

# Calculate 2nd quartile of Y, mean of Y, Standard Deviation of Y
y = round(quantile(Y, 0.50, na.rm = TRUE), 4)
meanY = round(mean(Y, na.rm=TRUE), 4)
stdY = round(sqrt(var(Y, na.rm=TRUE)), 4)
yvalues = c("2nd quartile(Y)=", y, "mean(Y)=", meanY, "Standard Deviation(Y)=", stdY)
print(paste(yvalues, collapse=" "))


# -------------------- Row 1------------------------
# (r1, c1: Count rows of X <= x AND Y <= y)
r1c1 = nrow(subset(hflights_df, ArrDelay <= x & DepDelay <= y))

# (r1, c2: Count rows of X <= x AND Y > y)
r1c2 = nrow(subset(hflights_df, ArrDelay <= x & DepDelay > y))

# (r1, c3: Total(r1c1 + r1c2))
r1c3 = r1c1 + r1c2


# -------------------- Row 2------------------------
# (r2, c1: Count rows of X > x AND Y <= y)
r2c1 = nrow(subset(hflights_df, ArrDelay > x & DepDelay <= y))

# (r2, c2: Count rows of X > x AND Y > y)
r2c2 = nrow(subset(hflights_df, ArrDelay > x & DepDelay > y))

# (r2, c3: Total(r2c1 + r2c2))
r2c3 = r2c1 + r2c2

# -------------------- Row 3------------------------
# (r3, c1: Total(r1c1 + r2c1)
r3c1 = r1c1 + r2c1

# (r3, c2: Total(r1c2 + r2c2)
r3c2 = r1c2 + r2c2

# (r3, c3: Total(r1c3 + r2c3)
r3c3 = r1c3 + r2c3

# Now construct the matrix of all values
countsTable = matrix(c(r1c1, r1c2, r1c3, r2c1, r2c2, r2c3, r3c1, r3c2, r3c3), nrow=3, ncol=3, byrow = TRUE)
colnames(countsTable) = c("<=2nd qtle(Y <= y)", "> 2nd qtle(Y > y)", "Total")
rownames(countsTable) = c("<=3rd qtle(X <= x)", "> 3rd qtle(X > x)", "Total")
print(countsTable)

# Calculate P(X>x | Y>y) = r2c2/r3c2
round(r2c2/r3c2, 4)
# Calculate P(X>x , Y>y) = r2c2/r3c3
round(r2c2/r3c3, 4)
# Calculate P(X<x | Y>y) = r1c2/r3c2
round(r1c2/r3c2, 4)

# Is P(A|B)= P(A)*P(B) ?
# P(A|B) = r2c2/r3c2
pA_OR_B = round(r2c2/r3c2, 4)
pA_OR_B
# P(A) = nrow(subset(hflights-df, ArrDelay > 11))/nrow(hflights_df)
pA = round(nrow(subset(hflights_df, ArrDelay > x))/nrow(hflights_df), 4)
pA
# P(B) = nrow(subset(hflights, DepDelay > 0)) / nrow(hflights_df)
pB = round(nrow(subset(hflights_df, DepDelay > y)) / nrow(hflights_df), 4)
pB
# 

pA_Times_pB = round(pA*pB, 4)
pA_Times_pB

# Chi Square Test
chisq.test(X,Y)
pValue = chisq.test(X,Y)$p.value
pValue


# Scatter Plot
ggplot(hflights_df, aes(x = X, y = Y)) + geom_point(color="red") + ggtitle("Arrival Delay Vs Departure Delay") + labs(x="Arrival Delay", y = "Departure Delay")

```

#### Descriptive and Inferenctial Statistics
```{r}
# Provide a 95% CI for the difference in the mean of the variables
ci95 = t.test(X,Y, conf.level = 0.95)
print(ci95$conf.int[1])
print(ci95$conf.int[2])

ci99 = t.test(X,Y, conf.level = 0.99)
print(ci99$conf.int[1])
print(ci99$conf.int[2])

correlation = cor.test(X,Y, conf.level = 0.99, na.action = "na.exclude")
print(correlation)
```

#### Linear Algebra & Correlation
```{r}
correlationMatrix = cor(cbind(X,Y), use="complete")
correlationMatrix
precisionMatrix = solve(correlationMatrix)

correlationMatrix %*% precisionMatrix

precisionMatrix %*% correlationMatrix

#xNorm = X - meanX
#yNorm = Y - meanY
#xyNorm <- cbind(X - meanX, Y - meanY)
covarience = cov(cbind(X - meanX, Y - meanY))
eigenValues = eigen(covarience)$values
eigenVectors= eigen(covarience)$vectors
round(eigenValues, 4)
round(eigenVectors,4)


```
#### Calculus Based Probability & Statistics
```{r}
shiftX = X + (abs(min(X)) + 1)
summary(shiftX)

# Fit the data to an exponential distribution
exponentialData = fitdistr(shiftX, "exponential")
exponentialData
summary(exponentialData)
lambda = exponentialData[[1]]
print (lambda)


# 1000 samples from the exponential PDF
sample = rexp(1000, lambda)
summary(sample)

# Histogram of the original X
hist(X, main = 'Original X', xlab = 'Arrival Delay')

# Histogram of the shifted value of X
hist(sample, main = 'Exponential Shifted X', xlab = ' ')

# 5th percentile
qexp(0.05, rate = lambda, lower.tail = TRUE, log.p = FALSE)

# 95th percentile
qexp(0.95, rate = lambda, lower.tail = TRUE, log.p = FALSE)


# 5th Percentile of ArrivalDelay
quantile(X, 0.05, na.rm = TRUE)

# 95% Percentile of ArrivalDelay
quantile(X, 0.95, na.rm = TRUE)

# 5th Percentile of Departure Delay
quantile(Y, 0.05, na.rm = TRUE)

# 95% Percentile of Departure Delay
quantile(Y, 0.95, na.rm = TRUE)
```



